sudo: required

dist: trusty

language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

env:
  global:
  - PYTHON_HOME="/opt/python/3.5.3"
  - M2_HOME="/usr/local/maven-3.3.9"

before_install:
  # Install MyPy
  - python3 -m pip install -U mypy
  # Install Linuxbrew
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
  - test -d ~/.linuxbrew && PATH="$HOME/.linuxbrew/bin:$PATH"
  - test -d /home/linuxbrew/.linuxbrew && PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  - test -r ~/.bash_profile && echo 'export PATH="$(brew --prefix)/bin:$PATH"' >>~/.bash_profile
  - echo 'export PATH="$(brew --prefix)/bin:$PATH"' >>~/.profile
  - brew --version
  - brew update
  # Install CML
  - brew tap cmlang/cml
  - brew install cml-compiler

script:
- cd cml-acceptance
- mvn clean install
