dist: trusty
sudo: required

language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

env:
  global:
    - PYTHON_HOME="/opt/python/3.5.3"
    - M2_HOME="/usr/local/maven-3.3.9"

before_install:
  # Checking Prerequisites:
  - test -d $PYTHON_HOME
  - test -d $PYTHON_HOME || ls /opt/python
  - test -d $M2_HOME
  - test -d $M2_HOME || ls /usr/local/maven-*
  # Configure Python
  - export PATH="$PYTHON_HOME/bin:$PATH"
  - test -w $HOME/.bash_profile && echo 'export PATH="$PYTHON_HOME/bin:$PATH"' >> $HOME/.bash_profile || true
  - echo 'export PATH="$PYTHON_HOME/bin:$PATH"' >> $HOME/.profile
  - python3 --version
  # Install MyPy
  - python3 -m pip install -U mypy
  # Install Linuxbrew
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
  - test -d $HOME/.linuxbrew && export PATH="$HOME/.linuxbrew/bin:$PATH" || true
  - test -d /home/linuxbrew/.linuxbrew && export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH" || true
  - test -d $HOME/.linuxbrew || test -d /home/linuxbrew/.linuxbrew
  - test -w $HOME/.bash_profile && echo 'export PATH="$(brew --prefix)/bin:$PATH"' >> $HOME/.bash_profile || true
  - echo 'export PATH="$(brew --prefix)/bin:$PATH"' >> $HOME/.profile
  - brew --version
  - brew update
  # Install CML
  - brew tap cmlang/cml
  - brew install cml-compiler

script:
- cd cml-acceptance
- mvn clean install
