sudo: required

dist: trusty

language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

env:
  - PYTHON_HOME="$(dirname $(dirname $(which python3)))"

before_install:
  - python3 -m pip install -U mypy
  - echo $M2_HOME
  - which mvn

script:
  - cd cml-acceptance
  - mvn clean install
