sudo: required

dist: trusty

language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

env:
  - PYTHON_HOME="$(dirname $(dirname $(which python3)))"

script:
  - cd cml-acceptance
  - mvn clean install
