sudo: required

dist: trusty

language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

env:
  global:
  - PYTHON_HOME="/opt/python/3.5.3"
  - M2_HOME="/usr/local/maven-3.3.9"

before_install:
  # Install MyPy
  - python3 -m pip install -U mypy
  # Install Linuxbrew
  - git clone https://github.com/Linuxbrew/brew.git $HOME/.linuxbrew
  - PATH="$HOME/.linuxbrew/bin:$PATH"
  - echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - brew --version
  - brew update
  # Install CML
  - brew tap cmlang/cml
  - brew install cml-compiler

script:
- cd cml-acceptance
- mvn clean install
