#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo Please specify the snapshot version as the only argument.
    exit 1
fi

CML_VERSION="$1-SNAPSHOT"
mvn versions:set -DnewVersion=${CML_VERSION}
if [ $? -ne 0 ]; then exit; fi

git add -A .
if [ $? -ne 0 ]; then exit; fi

git commit -m "Committing snapshot version: ${CML_VERSION}"
if [ $? -ne 0 ]; then exit; fi
